apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: geolocview-ingress
  namespace: default
spec:
  rules:
  - host: geolocview.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: geolocview-service
            port:
              number: 80

