# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# resources:
# - gotk-components.yaml
# - gotk-sync.yaml

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: my-kustomization
  namespace: flux-system
spec:
  interval: 1m
  path: "./clusters/geolocview-cluster-1"
  prune: true
  sourceRef:
    kind: GitRepository
    name: application-live
  validation: client
  ignore: |
    - .yamllint.yml

